unk18E4C:       dc.b   0
                dc.b   8
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $10
                dc.b   0
                dc.b $14
                dc.b   3
                dc.b   0
                dc.b   6
                dc.b $FF
                dc.b   3
                dc.b   0
                dc.b   1
                dc.b $FF
                dc.b   3
                dc.b   2
                dc.b   3
                dc.b $FF
                dc.b   3
                dc.b   4
                dc.b $FF
                dc.b   0