Ani1BuzzMissile:dc.b   0
                dc.b   4
                dc.b   0
                dc.b   8
                dc.b   7
                dc.b   0
                dc.b   1
                dc.b $FC
                dc.b   1
                dc.b   2
                dc.b   3
                dc.b $FF