debugstuff:     dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   1
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   1
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $61 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $61 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b $66 
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   0
                dc.b $11
                dc.b $10
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $11
                dc.b $11
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   1
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   1
                dc.b $11
                dc.b $16
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   1
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   0
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $10
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $11
                dc.b $16
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $61 
                dc.b   6
                dc.b $66 
                dc.b $66 
                dc.b $61 
                dc.b   0
                dc.b $66 
                dc.b $66
                dc.b $10
                dc.b   0
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   1
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b   6
                dc.b $61
                dc.b   0
                dc.b   0
                dc.b   1
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $FF
                dc.b $F1
                dc.b  $F
                dc.b $FF
                dc.b $FF
                dc.b $F1
                dc.b  $F
                dc.b $F1
                dc.b $11
                dc.b $11
                dc.b  $F
                dc.b $F1
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $FF
                dc.b $10
                dc.b  $F
                dc.b $FF
                dc.b $FF
                dc.b $10
                dc.b  $F
                dc.b $F1
                dc.b $11
                dc.b $10
                dc.b  $F
                dc.b $F1
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $FF
                dc.b $F1
                dc.b  $F
                dc.b $FF
                dc.b $FF
                dc.b $F1
                dc.b   1
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0