unk13374:       dc.b   0
                dc.b $7C
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b $50
                dc.b $F0
                dc.b   1
                dc.b $1E
                dc.b $20
                dc.b $80
                dc.b   0
                dc.b $B4
                dc.b $30
                dc.b $80
                dc.b   1
                dc.b  $E
                dc.b $50
                dc.b $80
                dc.b   1
                dc.b $C2
                dc.b $70
                dc.b $80
                dc.b   2
                dc.b $76
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $80
                dc.b   0
                dc.b   0