data15AA:       dc.b $60 
                dc.b $B2
                dc.b $60 
                dc.b $B0
                dc.b $60 
                dc.b $B8
                dc.b $60 
                dc.b $B6
                dc.b $60 
                dc.b $BC
                dc.b $60 
                dc.b $C6
                dc.b $60 
                dc.b $D2
                dc.b $60 
                dc.b $DE
                dc.b $53
                dc.b $48
                dc.b  $C
                dc.b $46
                dc.b   0
                dc.b $10
                dc.b $66
                dc.b   2
                dc.b $53
                dc.b $48
                dc.b $30
                dc.b   8
                dc.b $E2
                dc.b $48
                dc.b $64
                dc.b   2
                dc.b $52
                dc.b $48
                dc.b $4C
                dc.b $DF
                dc.b $3E
                dc.b $FF
                dc.b $4E
                dc.b $75
                dc.b $36
                dc.b  $B
                dc.b $12
                dc.b   4
                dc.b $D2
                dc.b   1
                dc.b $64
                dc.b  $A
                dc.b $53
                dc.b $46
                dc.b  $D
                dc.b   5
                dc.b $67
                dc.b   4
                dc.b   0
                dc.b $43
                dc.b $80
                dc.b   0
                dc.b $D2
                dc.b   1
                dc.b $64
                dc.b  $A
                dc.b $53
                dc.b $46
                dc.b  $D
                dc.b   5
                dc.b $67
                dc.b   4
                dc.b   6
                dc.b $43
                dc.b $40
                dc.b   0
                dc.b $D2
                dc.b   1
                dc.b $64
                dc.b  $A
                dc.b $53
                dc.b $46
                dc.b  $D
                dc.b   5
                dc.b $67
                dc.b   4
                dc.b   6
                dc.b $43
                dc.b $20
                dc.b   0
                dc.b $D2
                dc.b   1
                dc.b $64
                dc.b  $A
                dc.b $53
                dc.b $46
                dc.b  $D
                dc.b   5
                dc.b $67
                dc.b   4
                dc.b   0
                dc.b $43
                dc.b $10
                dc.b   0
                dc.b $D2
                dc.b   1
                dc.b $64
                dc.b  $A
                dc.b $53
                dc.b $46
                dc.b  $D
                dc.b   5
                dc.b $67
                dc.b   4
                dc.b   0
                dc.b $43
                dc.b   8
                dc.b   0
                dc.b $32
                dc.b   5
                dc.b $3E
                dc.b   6
                dc.b $9E
                dc.b $4D
                dc.b $64
                dc.b $28
                dc.b $3C
                dc.b   7
                dc.b   6
                dc.b $46
                dc.b   0
                dc.b $10
                dc.b $44
                dc.b $47
                dc.b $EF
                dc.b $69
                dc.b $1A
                dc.b $10
                dc.b $EF
                dc.b $3D
                dc.b $DE
                dc.b $47
                dc.b $CA
                dc.b $7B
                dc.b $70
                dc.b $2A
                dc.b $D2
                dc.b $45
                dc.b $30
                dc.b  $D
                dc.b $D0
                dc.b $40
                dc.b $C2
                dc.b $7B
                dc.b   0
                dc.b $20
                dc.b $D2
                dc.b $43
                dc.b $1A
                dc.b $18
                dc.b $E1
                dc.b $4D
                dc.b $1A
                dc.b $18
                dc.b $4E
                dc.b $75
                dc.b $67
                dc.b $10
                dc.b $EE
                dc.b $69
                dc.b $30
                dc.b  $D
                dc.b $D0
                dc.b $40
                dc.b $C2
                dc.b $7B
                dc.b   0
                dc.b  $A
                dc.b $D2
                dc.b $43
                dc.b $30
                dc.b  $D
                dc.b $60 
                dc.b $24
                dc.b $7C
                dc.b $10
                dc.b $60 
                dc.b $D8
                dc.b   0
                dc.b   1
                dc.b   0
                dc.b   3
                dc.b   0
                dc.b   7
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $1F
                dc.b   0
                dc.b $3F
                dc.b   0
                dc.b $7F
                dc.b   0
                dc.b $FF
                dc.b   1
                dc.b $FF
                dc.b   3
                dc.b $FF
                dc.b   7
                dc.b $FF
                dc.b  $F
                dc.b $FF
                dc.b $1F
                dc.b $FF
                dc.b $3F
                dc.b $FF
                dc.b $7F
                dc.b $FF
                dc.b $FF
                dc.b $FF