unk165A2:       dc.b   0
                dc.b   8
                dc.b   0
                dc.b $1D
                dc.b   0
                dc.b $46 
                dc.b   0
                dc.b $5B ; [
                dc.b   4
                dc.b $F8
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b   8
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $F8
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   8
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $10
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $10
                dc.b   4
                dc.b $F8
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b   8
                dc.b  $D
                dc.b   0
                dc.b   8
                dc.b $E0
                dc.b $F8
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   8
                dc.b  $D
                dc.b   0
                dc.b   8
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   4
                dc.b $F0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   4
                dc.b $10
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $E0
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b  $C
                dc.b $F0
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b   0
                dc.b   8
                dc.b   5
                dc.b   0
                dc.b  $C
                dc.b $10