unk1C6C2:       dc.b   0
                dc.b   6
                dc.b   0
                dc.b $11
                dc.b   0
                dc.b $1C
                dc.b   2
                dc.b $F0
                dc.b   7
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $F0
                dc.b   7
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b   2
                dc.b $F4
                dc.b   6
                dc.b   0
                dc.b   8
                dc.b $F4
                dc.b $F4
                dc.b   2
                dc.b   8
                dc.b   8
                dc.b   4
                dc.b   2
                dc.b $F0
                dc.b   7
                dc.b   0
                dc.b  $E
                dc.b $F0
                dc.b $F0
                dc.b   7
                dc.b   8
                dc.b  $E
                dc.b   0
                dc.b   0