buzzmaps:       dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $2B ; +
                dc.b   0
                dc.b $4A ; J
                dc.b   0
                dc.b $6E ; n
                dc.b   0
                dc.b $92
                dc.b   0
                dc.b $B1
                dc.b   6
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b   0
                dc.b $E8
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b   8
                dc.b   0
                dc.b $15
                dc.b $E8
                dc.b   4
                dc.b   4
                dc.b   0
                dc.b $18
                dc.b   0
                dc.b $F1
                dc.b   8
                dc.b   0
                dc.b $1A
                dc.b $EC
                dc.b $F1
                dc.b   4
                dc.b   0
                dc.b $1D
                dc.b   4
                dc.b   6
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b   0
                dc.b $E8
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b   8
                dc.b   0
                dc.b $15
                dc.b $E8
                dc.b   4
                dc.b   4
                dc.b   0
                dc.b $18
                dc.b   0
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b $1F
                dc.b $EC
                dc.b $F4
                dc.b   4
                dc.b   0
                dc.b $22 ; "
                dc.b   4
                dc.b   7
                dc.b   4
                dc.b   0
                dc.b   0
                dc.b $30 ; 0
                dc.b  $C
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b   0
                dc.b $E8
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b   8
                dc.b   0
                dc.b $15
                dc.b $E8
                dc.b   4
                dc.b   4
                dc.b   0
                dc.b $18
                dc.b   0
                dc.b $F1
                dc.b   8
                dc.b   0
                dc.b $1A
                dc.b $EC
                dc.b $F1
                dc.b   4
                dc.b   0
                dc.b $1D
                dc.b   4
                dc.b   7
                dc.b   4
                dc.b   4
                dc.b   0
                dc.b $31 ; 1
                dc.b  $C
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b   0
                dc.b $E8
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b   8
                dc.b   0
                dc.b $15
                dc.b $E8
                dc.b   4
                dc.b   4
                dc.b   0
                dc.b $18
                dc.b   0
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b $1F
                dc.b $EC
                dc.b $F4
                dc.b   4
                dc.b   0
                dc.b $22 ; "
                dc.b   4
                dc.b   6
                dc.b $F4
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $EC
                dc.b   4
                dc.b  $C
                dc.b   0
                dc.b   8
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b   0
                dc.b  $C
                dc.b  $C
                dc.b  $C
                dc.b   4
                dc.b   0
                dc.b  $D
                dc.b $F4
                dc.b $F1
                dc.b   8
                dc.b   0
                dc.b $1A
                dc.b $EC
                dc.b $F1
                dc.b   4
                dc.b   0
                dc.b $1D
                dc.b   4
                dc.b   4
                dc.b $F4
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $EC
                dc.b   4
                dc.b  $C
                dc.b   0
                dc.b   8
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b   0
                dc.b  $C
                dc.b  $C
                dc.b  $C
                dc.b   4
                dc.b   0
                dc.b  $D
                dc.b $F4
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b $1F
                dc.b $EC
                dc.b $F4
                dc.b   4
                dc.b   0
                dc.b $22 ; "
                dc.b   4