ghzcliff:       dc.b   0
                dc.b   8
                dc.b   0
                dc.b $59 ; Y
                dc.b   0
                dc.b $AA
                dc.b   1
                dc.b $28 ; (
                dc.b $10
                dc.b $C8
                dc.b  $E
                dc.b   0
                dc.b $57 ; W
                dc.b $10
                dc.b $D0
                dc.b  $D
                dc.b   0
                dc.b $63 ; c
                dc.b $F0
                dc.b $E0
                dc.b  $D
                dc.b   0
                dc.b $6B ; k
                dc.b $10
                dc.b $E0
                dc.b  $D
                dc.b   0
                dc.b $73 ; s
                dc.b $F0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $7B ; {
                dc.b $E0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $81
                dc.b $D0
                dc.b $F0
                dc.b  $D
                dc.b   0
                dc.b $87
                dc.b $10
                dc.b $F0
                dc.b  $D
                dc.b   0
                dc.b $8F
                dc.b $F0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $97
                dc.b $E0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $9B
                dc.b $D0
                dc.b   0
                dc.b  $D
                dc.b   0
                dc.b $9F
                dc.b $10
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $A7
                dc.b   0
                dc.b   0
                dc.b  $D
                dc.b   0
                dc.b $AB
                dc.b $E0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $B3
                dc.b $D0
                dc.b $10
                dc.b  $D
                dc.b   0
                dc.b $AB
                dc.b $10
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $B7
                dc.b   0
                dc.b $10
                dc.b $C8
                dc.b  $E
                dc.b   0
                dc.b $57 ; W
                dc.b $10
                dc.b $D0
                dc.b  $D
                dc.b   0
                dc.b $63 ; c
                dc.b $F0
                dc.b $E0
                dc.b  $D
                dc.b   0
                dc.b $6B ; k
                dc.b $10
                dc.b $E0
                dc.b  $D
                dc.b   0
                dc.b $73 ; s
                dc.b $F0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $7B ; {
                dc.b $E0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $BB
                dc.b $D0
                dc.b $F0
                dc.b  $D
                dc.b   0
                dc.b $87
                dc.b $10
                dc.b $F0
                dc.b  $D
                dc.b   0
                dc.b $8F
                dc.b $F0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $97
                dc.b $E0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $C1
                dc.b $D0
                dc.b   0
                dc.b  $D
                dc.b   0
                dc.b $9F
                dc.b $10
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $A7
                dc.b   0
                dc.b   0
                dc.b  $D
                dc.b   0
                dc.b $AB
                dc.b $E0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $B7
                dc.b $D0
                dc.b $10
                dc.b  $D
                dc.b   0
                dc.b $AB
                dc.b $10
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $B7
                dc.b   0
                dc.b $19
                dc.b $C8
                dc.b   6
                dc.b   0
                dc.b $5D ; ]
                dc.b $20
                dc.b $C8
                dc.b   6
                dc.b   0
                dc.b $57 ; W
                dc.b $10
                dc.b $D0
                dc.b   5
                dc.b   0
                dc.b $67 ; g
                dc.b   0
                dc.b $D0
                dc.b   5
                dc.b   0
                dc.b $63 ; c
                dc.b $F0
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $6F ; o
                dc.b $20
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $6B ; k
                dc.b $10
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $77 ; w
                dc.b   0
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $73 ; s
                dc.b $F0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $7B ; {
                dc.b $E0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $81
                dc.b $D0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $8B
                dc.b $20
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $87
                dc.b $10
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $93
                dc.b   0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $8F
                dc.b $F0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $97
                dc.b $E0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $9B
                dc.b $D0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $8B
                dc.b $20
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $8B
                dc.b $10
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $A7
                dc.b   0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $F0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $E0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $B3
                dc.b $D0
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $20
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $10
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $B7
                dc.b   0
                dc.b $19
                dc.b $C8
                dc.b   6
                dc.b   0
                dc.b $5D ; ]
                dc.b $20
                dc.b $C8
                dc.b   6
                dc.b   0
                dc.b $57 ; W
                dc.b $10
                dc.b $D0
                dc.b   5
                dc.b   0
                dc.b $67 ; g
                dc.b   0
                dc.b $D0
                dc.b   5
                dc.b   0
                dc.b $63 ; c
                dc.b $F0
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $6F ; o
                dc.b $20
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $6B ; k
                dc.b $10
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $77 ; w
                dc.b   0
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b $73 ; s
                dc.b $F0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $7B ; {
                dc.b $E0
                dc.b $D8
                dc.b   6
                dc.b   0
                dc.b $BB
                dc.b $D0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $8B
                dc.b $20
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $87
                dc.b $10
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $93
                dc.b   0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $8F
                dc.b $F0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $97
                dc.b $E0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b $C1
                dc.b $D0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $8B
                dc.b $20
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $8B
                dc.b $10
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $A7
                dc.b   0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $F0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $E0
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b $B7
                dc.b $D0
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $20
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $AB
                dc.b $10
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b $B7
                dc.b   0