ghzwallmap:     dc.b   0
                dc.b   6
                dc.b   0
                dc.b $1B
                dc.b   0
                dc.b $30 ; 0
                dc.b   4
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b   4
                dc.b $F8
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   4
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   4
                dc.b $E0
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b   0
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b $10
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b   0