unk18CBA:       dc.b   0
                dc.b   8
                dc.b   0
                dc.b $13
                dc.b   0
                dc.b $1E
                dc.b   0
                dc.b $29 ; )
                dc.b   2
                dc.b $F4
                dc.b  $E
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $18
                dc.b $10
                dc.b   2
                dc.b $F4
                dc.b  $E
                dc.b   0
                dc.b  $C
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $1C
                dc.b $10
                dc.b   2
                dc.b $F4
                dc.b  $E
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b $10
                dc.b $18
                dc.b $10
                dc.b   2
                dc.b $F4
                dc.b  $E
                dc.b   0
                dc.b  $C
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b $10
                dc.b $1C
                dc.b $10