ienith:         dc.b   0
                dc.b $18
                dc.b   0
                dc.b $1E
                dc.b   0
                dc.b $29
                dc.b   0
                dc.b $34
                dc.b   0
                dc.b $3F
                dc.b   0
                dc.b $4A
                dc.b   0
                dc.b $55
                dc.b   0
                dc.b $60 
                dc.b   0
                dc.b $6B
                dc.b   0
                dc.b $76
                dc.b   0
                dc.b $81
                dc.b   0
                dc.b $8C
                dc.b   1
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $10
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $14
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $18
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $1C
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $24
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $28
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $2C
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $30
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $34
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b $20
                dc.b $F8
                dc.b $EF
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   1
                dc.b $FF
                dc.b  $D
                dc.b   0
                dc.b $38 
                dc.b $F0