motobugmap:     dc.b   0
                dc.b  $E
                dc.b   0
                dc.b $23 ; #
                dc.b   0
                dc.b $38 ; 8
                dc.b   0
                dc.b $52 ; R
                dc.b   0
                dc.b $58 ; X
                dc.b   0
                dc.b $5E ; ^
                dc.b   0
                dc.b $64 ; d
                dc.b   4
                dc.b $F0
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $EC
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b   8
                dc.b $EC
                dc.b $F8
                dc.b   1
                dc.b   0
                dc.b  $C
                dc.b  $C
                dc.b   8
                dc.b   8
                dc.b   0
                dc.b  $E
                dc.b $F4
                dc.b   4
                dc.b $F1
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $EC
                dc.b   1
                dc.b  $C
                dc.b   0
                dc.b   8
                dc.b $EC
                dc.b $F9
                dc.b   1
                dc.b   0
                dc.b  $C
                dc.b  $C
                dc.b   9
                dc.b   8
                dc.b   0
                dc.b $11
                dc.b $F4
                dc.b   5
                dc.b $F0
                dc.b  $D
                dc.b   0
                dc.b   0
                dc.b $EC
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $14
                dc.b $EC
                dc.b $F8
                dc.b   1
                dc.b   0
                dc.b  $C
                dc.b  $C
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $18
                dc.b $EC
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $12
                dc.b $FC
                dc.b   1
                dc.b $FA
                dc.b   0
                dc.b   0
                dc.b $1A
                dc.b $10
                dc.b   1
                dc.b $FA
                dc.b   0
                dc.b   0
                dc.b $1B
                dc.b $10
                dc.b   1
                dc.b $FA
                dc.b   0
                dc.b   0
                dc.b $1C
                dc.b $10
                dc.b   0
                dc.b   0