unk1D6E0:       dc.b   0
                dc.b   4
                dc.b   0
                dc.b  $A
                dc.b   1
                dc.b $F8
                dc.b  $F
                dc.b   0
                dc.b   8
                dc.b $F0
                dc.b   2
                dc.b $F8
                dc.b  $F
                dc.b   0
                dc.b   8
                dc.b $E0
                dc.b $F8
                dc.b  $F
                dc.b   0
                dc.b   8
                dc.b   0
                dc.b   0