unk19630:       dc.b   0
                dc.b   8
                dc.b   0
                dc.b $27 ; '
                dc.b   0
                dc.b $46 
                dc.b   0
                dc.b $51 ; Q
                dc.b   6
                dc.b $DC
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $DC
                dc.b  $C
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b $E4
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b $E4
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b   4
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b   4
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b   6
                dc.b $DC
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b $DC
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $FC
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b $FC
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $1C
                dc.b  $C
                dc.b $10
                dc.b   0
                dc.b $E0
                dc.b $1C
                dc.b  $C
                dc.b $18
                dc.b   0
                dc.b   0
                dc.b   2
                dc.b   8
                dc.b   6
                dc.b   0
                dc.b $14
                dc.b $F0
                dc.b   0
                dc.b   6
                dc.b   0
                dc.b $14
                dc.b   0
                dc.b  $A
                dc.b $C8
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $C8
                dc.b  $C
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b $D0
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b $D0
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $F0
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b $F0
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $10
                dc.b  $F
                dc.b   0
                dc.b   4
                dc.b $E0
                dc.b $10
                dc.b  $F
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b $30 ; 0
                dc.b  $C
                dc.b $10
                dc.b   0
                dc.b $E0
                dc.b $30 ; 0
                dc.b  $C
                dc.b $18
                dc.b   0
                dc.b   0