unk1D108:       dc.b   0
                dc.b  $A
                dc.b   0
                dc.b $38 ; 8
                dc.b   0
                dc.b $66 
                dc.b   0
                dc.b $94
                dc.b   0
                dc.b $C2
                dc.b   9
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $60 
                dc.b $20
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $70 ; p
                dc.b $3C ; <
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $20
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   9
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $70 ; p
                dc.b $20
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $80
                dc.b $3C ; <
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $20
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   9
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $80
                dc.b $20
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $70 ; p
                dc.b $3C ; <
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $20
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   9
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $70 ; p
                dc.b $20
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $60 
                dc.b $3C ; <
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $20
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   8
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $20
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $20
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b   0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   0
                dc.b  $F
                dc.b $FF
                dc.b $2A 
                dc.b $C0
                dc.b   0