; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Apr 02 2021 20:14:56 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAT5O4N1NJ61M:
	dc.w DATAT5O4N1NJ61M_0-DATAT5O4N1NJ61M, DATAT5O4N1NJ61M_1-DATAT5O4N1NJ61M
	dc.w DATAT5O4N1NJ61M_2-DATAT5O4N1NJ61M, DATAT5O4N1NJ61M_3-DATAT5O4N1NJ61M
DATAT5O4N1NJ61M_0: dc.b $1
        dc.b $F0, $F, $80, $0, $F0
DATAT5O4N1NJ61M_1: dc.b $1
        dc.b $F0, $F, $80, $10, $F0
DATAT5O4N1NJ61M_2: dc.b $8
        dc.b $80, $F, $80, $10, $F0, $60, $F, $80, $10, $F0
        dc.b $40, $F, $80, $10, $F0, $20, $F, $80, $10, $F0
        dc.b $0, $F, $80, $10, $F0, $E0, $F, $80, $10, $F0
        dc.b $C0, $F, $80, $10, $F0, $A0, $F, $80, $10, $F0
        dc.b $0
DATAT5O4N1NJ61M_3: dc.b $8
        dc.b $80, $F, $80, $0, $F0, $60, $F, $80, $0, $F0
        dc.b $40, $F, $80, $0, $F0, $20, $F, $80, $0, $F0
        dc.b $0, $F, $80, $0, $F0, $E0, $F, $80, $0, $F0, $C0
        dc.b $F, $80, $0, $F0, $A0, $F, $80, $0, $F0, $0
	even