; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Apr 07 2021 12:09:23 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5QCXY8KSV8T:
	dc.w $0, DATA5QCXY8KSV8T_1-DATA5QCXY8KSV8T
	dc.w DATA5QCXY8KSV8T_2-DATA5QCXY8KSV8T
DATA5QCXY8KSV8T_1: dc.b $6
	dc.b $0, $C, $0, $F0, $0
	dc.b $0, $0, $0, $F3, $20
	dc.b $0, $0, $0, $F3, $30
	dc.b $0, $C, $0, $F4, $38
	dc.b $0, $8, $0, $F8, $60
	dc.b $0, $8, $0, $FB, $78
DATA5QCXY8KSV8T_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	even