; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Apr 24 2021 15:05:43 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA8ZUMO7KMBPT:
	dc.w $0, DATA8ZUMO7KMBPT_1-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_2-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_3-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_4-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_5-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_6-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_7-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_8-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_9-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_A-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_B-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_C-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_D-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_E-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_F-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_10-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_11-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_12-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_13-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_14-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_15-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_16-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_17-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_18-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_19-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_1A-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_1B-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_1C-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_1D-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_1E-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_1F-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_20-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_21-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_22-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_23-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_24-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_25-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_26-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_27-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_28-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_29-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_2A-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_2B-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_2C-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_2D-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_2E-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_2F-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_30-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_31-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_32-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_33-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_34-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_35-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_36-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_37-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_38-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_39-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_3A-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_3B-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_3C-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_3D-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_3E-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_3F-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_40-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_41-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_42-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_43-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_44-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_45-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_46-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_47-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_48-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_49-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_4A-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_4B-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_4C-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_4D-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_4E-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_4F-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_50-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_51-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_52-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_53-DATA8ZUMO7KMBPT
	dc.w DATA8ZUMO7KMBPT_54-DATA8ZUMO7KMBPT, DATA8ZUMO7KMBPT_55-DATA8ZUMO7KMBPT
DATA8ZUMO7KMBPT_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATA8ZUMO7KMBPT_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA8ZUMO7KMBPT_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA8ZUMO7KMBPT_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA8ZUMO7KMBPT_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATA8ZUMO7KMBPT_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATA8ZUMO7KMBPT_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATA8ZUMO7KMBPT_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATA8ZUMO7KMBPT_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATA8ZUMO7KMBPT_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATA8ZUMO7KMBPT_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATA8ZUMO7KMBPT_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATA8ZUMO7KMBPT_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATA8ZUMO7KMBPT_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATA8ZUMO7KMBPT_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATA8ZUMO7KMBPT_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATA8ZUMO7KMBPT_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATA8ZUMO7KMBPT_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATA8ZUMO7KMBPT_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATA8ZUMO7KMBPT_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATA8ZUMO7KMBPT_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATA8ZUMO7KMBPT_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATA8ZUMO7KMBPT_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATA8ZUMO7KMBPT_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATA8ZUMO7KMBPT_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATA8ZUMO7KMBPT_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATA8ZUMO7KMBPT_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATA8ZUMO7KMBPT_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATA8ZUMO7KMBPT_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATA8ZUMO7KMBPT_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA8ZUMO7KMBPT_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA8ZUMO7KMBPT_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA8ZUMO7KMBPT_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA8ZUMO7KMBPT_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA8ZUMO7KMBPT_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA8ZUMO7KMBPT_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA8ZUMO7KMBPT_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA8ZUMO7KMBPT_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA8ZUMO7KMBPT_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA8ZUMO7KMBPT_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA8ZUMO7KMBPT_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA8ZUMO7KMBPT_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA8ZUMO7KMBPT_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA8ZUMO7KMBPT_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA8ZUMO7KMBPT_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA8ZUMO7KMBPT_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATA8ZUMO7KMBPT_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA8ZUMO7KMBPT_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA8ZUMO7KMBPT_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATA8ZUMO7KMBPT_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATA8ZUMO7KMBPT_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATA8ZUMO7KMBPT_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATA8ZUMO7KMBPT_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATA8ZUMO7KMBPT_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA8ZUMO7KMBPT_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATA8ZUMO7KMBPT_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATA8ZUMO7KMBPT_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA8ZUMO7KMBPT_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATA8ZUMO7KMBPT_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA8ZUMO7KMBPT_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA8ZUMO7KMBPT_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA8ZUMO7KMBPT_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA8ZUMO7KMBPT_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA8ZUMO7KMBPT_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA8ZUMO7KMBPT_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA8ZUMO7KMBPT_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA8ZUMO7KMBPT_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATA8ZUMO7KMBPT_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATA8ZUMO7KMBPT_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATA8ZUMO7KMBPT_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA8ZUMO7KMBPT_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA8ZUMO7KMBPT_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATA8ZUMO7KMBPT_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATA8ZUMO7KMBPT_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATA8ZUMO7KMBPT_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATA8ZUMO7KMBPT_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATA8ZUMO7KMBPT_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATA8ZUMO7KMBPT_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATA8ZUMO7KMBPT_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
	even