spikemap:       dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $1C
                dc.b   0
                dc.b $2C ; ,
                dc.b   0
                dc.b $32 ; 2
                dc.b   0
                dc.b $42 ; B
                dc.b   0
                dc.b $61 
                dc.b   3
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $EC
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $FC
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b  $C
                dc.b   3
                dc.b $EC
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $FC
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b  $C
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   1
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $FC
                dc.b   3
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $E4
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $FC
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $14
                dc.b   6
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $C0
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $D8
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $F0
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b   8
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $20
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $38 ; 8
                dc.b   1
                dc.b $FC
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   0