unk_66DC:       dc.b   0
                dc.b   4
                dc.b   0
                dc.b $19
                dc.b   4
                dc.b $F0
                dc.b  $A
                dc.b   0
                dc.b $89
                dc.b $E0
                dc.b $F0
                dc.b  $A
                dc.b   8
                dc.b $89
                dc.b   8
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b $92
                dc.b $F8
                dc.b   8
                dc.b  $C
                dc.b   0
                dc.b $96
                dc.b $F0
                dc.b   4
                dc.b $E8
                dc.b  $F
                dc.b   0
                dc.b $9A
                dc.b $E0
                dc.b $E8
                dc.b  $F
                dc.b   8
                dc.b $9A
                dc.b   0
                dc.b   8
                dc.b  $D
                dc.b   0
                dc.b $AA
                dc.b $E0
                dc.b   8
                dc.b  $D
                dc.b   8
                dc.b $AA
                dc.b   0