springmap:      dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $17
                dc.b   0
                dc.b $1D
                dc.b   0
                dc.b $2D ; -
                dc.b   0
                dc.b $33 ; 3
                dc.b   0
                dc.b $39 ; 9
                dc.b   2
                dc.b $F8
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b   4
                dc.b $F0
                dc.b   1
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b   3
                dc.b $E8
                dc.b  $C
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $F0
                dc.b   5
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b  $C
                dc.b $F0
                dc.b   1
                dc.b $F0
                dc.b   7
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b   1
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $F8
                dc.b   4
                dc.b $F0
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b $10
                dc.b $F8
                dc.b   9
                dc.b   0
                dc.b   8
                dc.b $F8
                dc.b $F0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $F8
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b   3
                dc.b $F8