unk19ED4:       dc.b   0
                dc.b   8
                dc.b   0
                dc.b $13
                dc.b   0
                dc.b $1E
                dc.b   0
                dc.b $13
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b   0
                dc.b   4
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b   8
                dc.b   4
                dc.b   0
                dc.b   2
                dc.b $F5
                dc.b   5
                dc.b $FF
                dc.b $FC
                dc.b $F0
                dc.b $F5
                dc.b   5
                dc.b   7
                dc.b $FC
                dc.b   0
                dc.b $F8
                dc.b   5
                dc.b   0
                dc.b   0
                dc.b $F8