unk1DC1C:       dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $12
                dc.b   0
                dc.b $27 ; '
                dc.b   0
                dc.b $32 ; 2
                dc.b   0
                dc.b $47 ; G
                dc.b   0
                dc.b $57 ; W
                dc.b   1
                dc.b $F0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b $F0
                dc.b   4
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b   0
                dc.b   2
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b $F0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $61 
                dc.b $F0
                dc.b   4
                dc.b $E6
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b $E0
                dc.b $E6
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b   0
                dc.b   3
                dc.b $D9
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b $F0
                dc.b $F3
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b $F0
                dc.b  $D
                dc.b  $F
                dc.b   0
                dc.b $81
                dc.b $F0
                dc.b   1
                dc.b $F0
                dc.b  $F
                dc.b   0
                dc.b $21 ; !
                dc.b $F0
                dc.b   0