Yadrin_Map:     dc.b   0
                dc.b  $C
                dc.b   0
                dc.b $26 ; &
                dc.b   0
                dc.b $40 ; @
                dc.b   0
                dc.b $5A ; Z
                dc.b   0
                dc.b $74 ; t
                dc.b   0
                dc.b $8E
                dc.b   5
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b $F4
                dc.b $FC
                dc.b  $E
                dc.b   0
                dc.b   3
                dc.b $EC
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b  $F
                dc.b $FC
                dc.b $F4
                dc.b   2
                dc.b   0
                dc.b $11
                dc.b  $C
                dc.b   4
                dc.b   9
                dc.b   0
                dc.b $31 ; 1
                dc.b $FC
                dc.b   5
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b $14
                dc.b $F4
                dc.b $FC
                dc.b  $E
                dc.b   0
                dc.b $17
                dc.b $EC
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b  $F
                dc.b $FC
                dc.b $F4
                dc.b   2
                dc.b   0
                dc.b $11
                dc.b  $C
                dc.b   4
                dc.b   9
                dc.b   0
                dc.b $31 ; 1
                dc.b $FC
                dc.b   5
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b $23 ; #
                dc.b $F4
                dc.b   4
                dc.b  $D
                dc.b   0
                dc.b $29 ; )
                dc.b $EC
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b  $F
                dc.b $FC
                dc.b $F4
                dc.b   2
                dc.b   0
                dc.b $11
                dc.b  $C
                dc.b   4
                dc.b   9
                dc.b   0
                dc.b $31 ; 1
                dc.b $FC
                dc.b   5
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b   0
                dc.b $F4
                dc.b $FC
                dc.b  $E
                dc.b   0
                dc.b   3
                dc.b $EC
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b  $F
                dc.b $FC
                dc.b $F4
                dc.b   2
                dc.b   0
                dc.b $11
                dc.b  $C
                dc.b   4
                dc.b   9
                dc.b   0
                dc.b $37 ; 7
                dc.b $FC
                dc.b   5
                dc.b $F4
                dc.b   8
                dc.b   0
                dc.b $14
                dc.b $F4
                dc.b $FC
                dc.b  $E
                dc.b   0
                dc.b $17
                dc.b $EC
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b  $F
                dc.b $FC
                dc.b $F4
                dc.b   2
                dc.b   0
                dc.b $11
                dc.b  $C
                dc.b   4
                dc.b   9
                dc.b   0
                dc.b $37 ; 7
                dc.b $FC
                dc.b   5
                dc.b $F4
                dc.b   9
                dc.b   0
                dc.b $23 ; #
                dc.b $F4
                dc.b   4
                dc.b  $D
                dc.b   0
                dc.b $29 ; )
                dc.b $EC
                dc.b $EC
                dc.b   4
                dc.b   0
                dc.b  $F
                dc.b $FC
                dc.b $F4
                dc.b   2
                dc.b   0
                dc.b $11
                dc.b  $C
                dc.b   4
                dc.b   9
                dc.b   0
                dc.b $37 ; 7
                dc.b $FC