data1A6A:       dc.b  $E
                dc.b $C0
                dc.b  $E
                dc.b $A0
                dc.b  $E
                dc.b $80
                dc.b  $E
                dc.b $60 
                dc.b  $E
                dc.b $40
                dc.b  $E
                dc.b $20
                dc.b  $E
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b  $A
                dc.b   0
                dc.b   8
                dc.b   0
                dc.b   6
                dc.b   0
                dc.b   8
                dc.b   0
                dc.b  $A
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b  $E
                dc.b   0
                dc.b  $E
                dc.b $20
                dc.b  $E
                dc.b $40
                dc.b  $E
                dc.b $60 
                dc.b  $E
                dc.b $80
                dc.b  $E
                dc.b $A0
                dc.b  $E
                dc.b $C0
                dc.b  $E
                dc.b $A0
                dc.b  $E
                dc.b $80
                dc.b  $E
                dc.b $60 
                dc.b  $E
                dc.b $40
                dc.b  $E
                dc.b $20
                dc.b  $E
                dc.b   0
                dc.b  $C
                dc.b   0
                dc.b  $A
                dc.b   0
                dc.b   8
                dc.b   0
                dc.b   6
                dc.b   0