PalettePointers:dc.l Pal_Sega
                dc.w $FB00
                dc.w $1F
                dc.l Pal_Title
                dc.w $FB00
                dc.w $1F
                dc.l Pal_LevelSel
                dc.w $FB00
                dc.w $1F
                dc.l Pal_Sonic
                dc.w $FB00
                dc.w 7
                dc.l Pal_GHZ
                dc.w $FB20
                dc.w $17
                dc.l Pal_LZ
                dc.w $FB20
                dc.w $17
                dc.l Pal_MZ
                dc.w $FB20
                dc.w $17
                dc.l Pal_SLZ
                dc.w $FB20
                dc.w $17
                dc.l Pal_SZ
                dc.w $FB20
                dc.w $17
                dc.l Pal_CWZ
                dc.w $FB20
                dc.w $17
                dc.l Pal_Special
                dc.w $FB00
                dc.w $1F
                dc.l Pal_Unused
                dc.w $FB00
                dc.w $1F