nerq:           dc.l Map_SSWalls
                dc.w $142
                dc.l Map_SSWalls
                dc.w $2142
                dc.l Map_SSWalls
                dc.w $4142
                dc.l Map_SSWalls
                dc.w $6142
                dc.l Map_SSWalls
                dc.w $142
                dc.l Map_SSWalls
                dc.w $142
                dc.l Map_SSWalls
                dc.w $142
                dc.l Map_SSWalls
                dc.w $142
                dc.l Map_SSWalls
                dc.w $2142
                dc.l Map_SSWalls
                dc.w $2142
                dc.l Map_SSWalls
                dc.w $2142
                dc.l Map_SSWalls
                dc.w $2142
                dc.l Map_SSWalls
                dc.w $4142
                dc.l Map_SSWalls
                dc.w $4142
                dc.l Map_SSWalls
                dc.w $4142
                dc.l Map_SSWalls
                dc.w $4142
                dc.l Map_Signpost_Sparkle
                dc.w $27B2
                dc.l unk_C6C2
                dc.w $23B
                dc.l unk_10C78
                dc.w $251
                dc.l unk_10C88
                dc.w $251
                dc.l unk_10C78
                dc.w $263
                dc.l unk_10C88
                dc.w $263
                dc.l Map_Signpost_Sparkle+$4000000
                dc.w $27B2
                dc.l Map_Signpost_Sparkle+$5000000
                dc.w $27B2
                dc.l Map_Signpost_Sparkle+$6000000
                dc.w $27B2
                dc.l Map_Signpost_Sparkle+$7000000
                dc.w $27B2
                dc.l unk_C6C2+$1000000
                dc.w $23B
                dc.l unk_C6C2+$2000000
                dc.w $23B